apiVersion: training.educates.dev/v1beta1
kind: TrainingPortal
metadata:
  name: lab-jupyter-workshop
spec:
  portal:
    registration:
      type: anonymous
    updates:
      workshop: true
    sessions:
      maximum: 1
    workshop:
      defaults:
        reserved: 1
        initial: 0
  workshops:
  - name: lab-jupyter-workshop
    expires: 60m
    orphaned: 15m
