apiVersion: training.educates.dev/v1beta1
kind: Workshop
metadata:
  name: lab-jupyter-workshop
spec:
  title: "Jupyter Workshop"
  description: Demonstration of using Jupyter in a workshop.
  workshop:
    image: conda-environment:*
    files:
    - image:
        url: $(image_repository)/lab-jupyter-workshop-files:latest
      includePaths:
      - /workshop/**
      - /exercises/**
      - /README.md
  session:
    resources:
      memory: 2Gi
      storage: 5Gi
    namespaces:
      budget: medium
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
    env:
    - name: ENABLE_JUPYTERLAB
      value: "true"
    ingresses:
    - name: jupyter
      port: 8888
    dashboards:
    - name: Jupyter
      url: "$(ingress_protocol)://jupyter-$(session_namespace).$(ingress_domain)/"
