name: Publish Frontend

on:
  push:
    branches:
      - main

jobs:
  publish-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub container registry
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io

      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          context: projects/frontend
          platforms: linux/amd64
          tags: ghcr.io/${{github.repository}}-frontend:1.0
          push: true
